export const SUPPORTED_UPLOAD_FILE_TYPES = [
  { fileFormat: '.c', mimetype: 'text/x-c' },
  { fileFormat: '.cpp', mimetype: 'text/x-c++' },
  { fileFormat: '.docx', mimetype: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' },
  { fileFormat: '.html', mimetype: 'text/html' },
  { fileFormat: '.java', mimetype: 'text/x-java' },
  { fileFormat: '.json', mimetype: 'application/json' },
  { fileFormat: '.md', mimetype: 'text/markdown' },
  { fileFormat: '.pdf', mimetype: 'application/pdf' },
  { fileFormat: '.php', mimetype: 'text/x-php' },
  { fileFormat: '.pptx', mimetype: 'application/vnd.openxmlformats-officedocument.presentationml.presentation' },
  { fileFormat: '.py', mimetype: 'text/x-python' },
  { fileFormat: '.py', mimetype: 'text/x-script.python' },
  { fileFormat: '.rb', mimetype: 'text/x-ruby' },
  { fileFormat: '.tex', mimetype: 'text/x-tex' },
  { fileFormat: '.txt', mimetype: 'text/plain' },
];
